CONTIKI=../..

all: example-use-case

TARGET=sky
WITH_COAP=13
WITH_UIP6=1
UIP_CONF_IPV6=1
CFLAGS+= -DUIP_CONF_IPV6_RPL
CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

CFLAGS += -DWITH_COAP=13
CFLAGS += -DREST=coap_rest_implementation
CFLAGS += -DUIP_CONF_TCP=0
APPS += er-coap-13
APPS += erbium

PROJECT_SOURCEFILES += simple-energest.c

include $(CONTIKI)/Makefile.include
